### ISSUE TITLE
[SERVER] internal error after NewTownRequest

### ISSUE THREAD

**Issue by ArtemPopof** [abbysoft-team/GardarikeOnlineServer#6]
time="2021-03-08T15:07:23Z" level=error msg="Failed to update character" error="could not find name maxPopulation in &model.Character{ID:29, AccountID:62, Name:\"America\", MaxPopulation:0x64, CurrentPopulation:0x0, Towns:[]model.Town(nil), Resources:model.Resources{CharacterID:29, Wood:0x1e, Food:0x32, Stone:0x1e, Leather:0xa}}" module=logic

**Comment by JorgenPo** [comment]
Fixed
